import type { CSSProperties, RefObject } from "react";
import type { Annotation, Project, SpeedEffect, ZoomEffect } from "../../../types/project";

export interface EditorMainPaneProps {
  project: Project;
  videoRef: RefObject<HTMLVideoElement | null>;
  videoSrc: string;
  videoZoomStyle: CSSProperties;
  activeZoom: ZoomEffect | null;
  activeSpeed: SpeedEffect | null;
  effectivePlaybackRate: number;
  currentTime: number;
  isPlaying: boolean;
  previewFilter: string;
  selectedAnnotationId: string | null;
  cameraSrc: string;
  onAnnotationPositionChange: (annotationId: string, x: number, y: number) => void;
  onCameraOverlayCustomPositionChange: (x: number, y: number) => void;
  sourceToEditedTime: (sourceTime: number) => number;
  editedDuration: number;
  canUndo: boolean;
  canRedo: boolean;
  canDelete: boolean;
  canDeleteZoom: boolean;
  canDeleteSpeed: boolean;
  canDeleteSegment: boolean;
  canDeleteAnnotation: boolean;
  annotationInsertMode: "outline" | "blur" | "text" | "arrow";
  selectedTool: "cut" | "zoom" | "speed" | "annotation" | null;
  onTogglePlay: () => void;
  onSkipBackward: () => void;
  onSkipForward: () => void;
  onUndo: () => void;
  onRedo: () => void;
  onDelete: () => void;
  onToggleTool: (tool: "cut" | "zoom" | "speed" | "annotation") => void;
  selectedZoom: ZoomEffect | null;
  selectedSpeed: SpeedEffect | null;
  selectedAnnotation: Annotation | null;
  onZoomCommit: (updates: Partial<ZoomEffect>) => void;
  onCloseZoom: () => void;
  onZoomDraftChange: (draft: { scale: number; x: number; y: number }) => void;
  onSpeedCommit: (updates: Partial<SpeedEffect>) => void;
  onCloseSpeed: () => void;
  onSpeedDraftChange: (draft: { speed: number }) => void;
  onAnnotationCommit: (updates: Partial<Annotation>) => void;
  onDuplicateAnnotation: () => void;
  onCloseAnnotation: () => void;
}
