import { EditorMainPane } from "./EditorMainPane";
import { EditorTimelinePanel } from "./EditorTimelinePanel";
import type { EditorLayoutContentProps } from "./EditorLayoutContent.types";

export function EditorLayoutContent({
  project,
  duration,
  videoRef,
  videoSrc,
  videoZoomStyle,
  activeZoom,
  activeSpeed,
  effectivePlaybackRate,
  currentTime,
  isPlaying,
  previewFilter,
  selectedAnnotationId,
  cameraSrc,
  onAnnotationPositionChange,
  onCameraOverlayCustomPositionChange,
  sourceToEditedTime,
  editedDuration,
  canUndo,
  canRedo,
  canDelete,
  canDeleteZoom,
  canDeleteSpeed,
  canDeleteSegment,
  canDeleteAnnotation,
  annotationInsertMode,
  selectedTool,
  onTogglePlay,
  onSkipBackward,
  onSkipForward,
  onUndo,
  onRedo,
  onDeleteSelected,
  onToggleTool,
  selectedZoom,
  selectedSpeed,
  selectedAnnotation,
  onZoomCommit,
  onCloseZoom,
  onZoomDraftChange,
  onSpeedCommit,
  onCloseSpeed,
  onSpeedDraftChange,
  onAnnotationCommit,
  onDuplicateAnnotation,
  onCloseAnnotation,
  screenWaveform,
  microphoneWaveform,
  selectedSegmentId,
  selectedZoomId,
  selectedSpeedId,
  onSeek,
  onSelectSegment,
  onSelectZoom,
  onUpdateZoom,
  onSelectSpeed,
  onUpdateSpeed,
  onSelectAnnotation,
  onUpdateAnnotation,
}: EditorLayoutContentProps) {
  return (
    <>
      <EditorMainPane
        project={project}
        videoRef={videoRef}
        videoSrc={videoSrc}
        videoZoomStyle={videoZoomStyle}
        activeZoom={activeZoom}
        activeSpeed={activeSpeed}
        effectivePlaybackRate={effectivePlaybackRate}
        currentTime={currentTime}
        isPlaying={isPlaying}
        previewFilter={previewFilter}
        selectedAnnotationId={selectedAnnotationId}
        cameraSrc={cameraSrc}
        onAnnotationPositionChange={onAnnotationPositionChange}
        onCameraOverlayCustomPositionChange={onCameraOverlayCustomPositionChange}
        sourceToEditedTime={sourceToEditedTime}
        editedDuration={editedDuration}
        canUndo={canUndo}
        canRedo={canRedo}
        canDelete={canDelete}
        canDeleteZoom={canDeleteZoom}
        canDeleteSpeed={canDeleteSpeed}
        canDeleteSegment={canDeleteSegment}
        canDeleteAnnotation={canDeleteAnnotation}
        annotationInsertMode={annotationInsertMode}
        selectedTool={selectedTool}
        onTogglePlay={onTogglePlay}
        onSkipBackward={onSkipBackward}
        onSkipForward={onSkipForward}
        onUndo={onUndo}
        onRedo={onRedo}
        onDelete={onDeleteSelected}
        onToggleTool={onToggleTool}
        selectedZoom={selectedZoom}
        selectedSpeed={selectedSpeed}
        selectedAnnotation={selectedAnnotation}
        onZoomCommit={onZoomCommit}
        onCloseZoom={onCloseZoom}
        onZoomDraftChange={onZoomDraftChange}
        onSpeedCommit={onSpeedCommit}
        onCloseSpeed={onCloseSpeed}
        onSpeedDraftChange={onSpeedDraftChange}
        onAnnotationCommit={onAnnotationCommit}
        onDuplicateAnnotation={onDuplicateAnnotation}
        onCloseAnnotation={onCloseAnnotation}
      />

      <EditorTimelinePanel
        project={project}
        duration={duration}
        currentTime={currentTime}
        screenWaveform={screenWaveform}
        microphoneWaveform={microphoneWaveform}
        selectedTool={selectedTool}
        selectedSegmentId={selectedSegmentId}
        selectedZoomId={selectedZoomId}
        selectedSpeedId={selectedSpeedId}
        selectedAnnotationId={selectedAnnotationId}
        onSeek={onSeek}
        onSelectSegment={onSelectSegment}
        onSelectZoom={onSelectZoom}
        onUpdateZoom={onUpdateZoom}
        onSelectSpeed={onSelectSpeed}
        onUpdateSpeed={onUpdateSpeed}
        onSelectAnnotation={onSelectAnnotation}
        onUpdateAnnotation={onUpdateAnnotation}
      />
    </>
  );
}
