import type { CSSProperties, RefObject } from "react";
import type { Annotation, Project, SpeedEffect, ZoomEffect } from "../../../types/project";

export interface EditorPageLayoutProps {
  project: Project;
  isDirty: boolean;
  activeExportCount: number;
  duration: number;
  videoRef: RefObject<HTMLVideoElement | null>;
  videoSrc: string;
  videoZoomStyle: CSSProperties;
  activeZoom: ZoomEffect | null;
  activeSpeed: SpeedEffect | null;
  effectivePlaybackRate: number;
  currentTime: number;
  isPlaying: boolean;
  previewFilter: string;
  selectedAnnotationId: string | null;
  cameraSrc: string;
  onAnnotationPositionChange: (annotationId: string, x: number, y: number) => void;
  onCameraOverlayCustomPositionChange: (x: number, y: number) => void;
  sourceToEditedTime: (sourceTime: number) => number;
  editedDuration: number;
  canUndo: boolean;
  canRedo: boolean;
  canDelete: boolean;
  canDeleteZoom: boolean;
  canDeleteSpeed: boolean;
  canDeleteSegment: boolean;
  canDeleteAnnotation: boolean;
  annotationInsertMode: "outline" | "blur" | "text" | "arrow";
  selectedTool: "cut" | "zoom" | "speed" | "annotation" | null;
  selectedSegmentId: string | null;
  selectedZoomId: string | null;
  selectedSpeedId: string | null;
  screenWaveform: number[];
  microphoneWaveform: number[];
  selectedZoom: ZoomEffect | null;
  selectedSpeed: SpeedEffect | null;
  selectedAnnotation: Annotation | null;
  onRenameProject: (name: string) => void;
  onBack: () => void;
  onExport: () => void;
  onOpenVideos: () => void;
  onOpenInNewWindow: () => void;
  onTogglePlay: () => void;
  onSkipBackward: () => void;
  onSkipForward: () => void;
  onUndo: () => void;
  onRedo: () => void;
  onDeleteSelected: () => void;
  onToggleTool: (tool: "cut" | "zoom" | "speed" | "annotation") => void;
  onZoomCommit: (updates: Partial<ZoomEffect>) => void;
  onCloseZoom: () => void;
  onZoomDraftChange: (draft: { scale: number; x: number; y: number }) => void;
  onSpeedCommit: (updates: Partial<SpeedEffect>) => void;
  onCloseSpeed: () => void;
  onSpeedDraftChange: (draft: { speed: number }) => void;
  onAnnotationCommit: (updates: Partial<Annotation>) => void;
  onDuplicateAnnotation: () => void;
  onCloseAnnotation: () => void;
  onSeek: (time: number) => void;
  onSelectSegment: (segmentId: string | null) => void;
  onSelectZoom: (zoomId: string | null) => void;
  onUpdateZoom: (zoomId: string, updates: Partial<ZoomEffect>) => void;
  onSelectSpeed: (speedId: string | null) => void;
  onUpdateSpeed: (speedId: string, updates: Partial<SpeedEffect>) => void;
  onSelectAnnotation: (annotationId: string | null) => void;
  onUpdateAnnotation: (annotationId: string, updates: Partial<Annotation>) => void;
  onCameraOverlayPositionChange: (
    position: "top-left" | "top-right" | "bottom-left" | "bottom-right" | "custom"
  ) => void;
  onCameraOverlayScaleChange: (scale: number) => void;
  onCameraOverlayMarginChange: (margin: number) => void;
  onAudioSystemVolumeChange: (volume: number) => void;
  onAudioMicrophoneVolumeChange: (volume: number) => void;
  onMicrophoneNoiseGateChange: (enabled: boolean) => void;
  onColorBrightnessChange: (value: number) => void;
  onColorContrastChange: (value: number) => void;
  onColorSaturationChange: (value: number) => void;
  onResetColorCorrection: () => void;
  showExportModal: boolean;
  onSetShowExportModal: (open: boolean) => void;
  onSaveProject: () => Promise<void>;
}
